
import 'package:get/get.dart';

class MyLocale implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    "ar":{
      "English": "English",
      "Arabic": "العربية",
      "to any country you want to sent your gift ?": "إلى أي دولة تود إرسال هديتك ؟",
      "Egypt": "مصر",
      "Algeria": "الجزائر",
      "UAE": "الامارات",
      "Mauritania": "موريتانيا",
      "Tunisia":"تونس",
      "Syria": "سوريا",
      "Iraq": "العراق",
      "Oman": "عمان",
      "Palastine": "فلسطين",
      "Qatar": "قطر",
      "Create new account": "تسجيل حساب جديد",
      "Please enter you information to continue":"من فضلك ادخل بياناتك الخاصة للمتابعة",
      "Your name": "اسمك الشخصي",
      "Phone number": "رقم الجوال",
      "Birth date": "تاريخ الميلاد",
      "Email": "البريد الالكتروني",
      "Password": "كلمة المرور",
      "Password confirmation": "تأكيد كلمة المرور",
      "Or sign with": "أو سجل الدخول عبر",
      "Facebook": "فيس بوك",
      "Google": "جوجل",
      "Already have an account?  ": "لديك حساب بالفعل؟  ",
      "Don't have an account?  ": "ليس لديك حساب ؟  ",
      "Forget password ?": "نسيت كلمة السر ؟",
      "Sign in": "تسجيل الدخول",
      "Sign up": "حساب جديد",
      "Enter your name please": "ادخل اسمك الشخصي من فضلك",
      "Enter your phone number please": "ادخل رقمك الجوال من فضلك",
      "Enter your birth date please": "ادخل تاريخ ميلادك من فضلك",
      "Enter your email please": "ادخل عنوان بريدك الالكتروني من فضلك",
      "Your email must contain '@'": "بريدك الالكتروني يجب ان يحتوي علي '@'",
      "Your email must contain '.'": "بريدك الالكتروني يجب ان يحتوي علي '.'",
      "Enter your password please": "ادخل كلمة المرور من فضلك",
      "Password mustn't less than 8 characters": "كلمة المرور يجب الا تقل عن 8 احرف",
      "Enter your confirmation password please": "ادخل تأكيد كلمة المرور من فضلك",
      "Password doesn't match": "كلمة المرور غير متطابقه",
      "OTP Code": "كود التحقق",
      "Please enter OTP code": "من فضلك ادخل رمز التأكيد",
      "Check": "تحقق",
      "Reset password": "استعادة كلمة المرور",
      "Set Password": "تعيين كلمة المرور",
      "Please enter your account mobile number": "من فضلك ادخل رقم الجوال الخاص بحسابك",
      "Continue": "متابعة",
      "Set new Password": "تعيين كلمة مرور جديدة",
      "Please enter the new password": "من فضلك ادخل كلمة المرور الجديدة",
      "New Password": "كلمة المرور الجديدة",
      "New Password confirmation": "اعادة كلمة المرور الجديدة",
    },
    "en":{
      "Arabic":"Arabic",
      "English": "English",
      "to any country you want to sent your gift ?":"to any country you want to sent your gift ?",
      "Egypt": "Egypt",
      "Algeria": "Algeria",
      "UAE": "UAE",
      "Mauritania": "Mauritania",
      "Tunisia":"Tunisia",
      "Syria": "Syria",
      "Iraq": "Iraq",
      "Oman": "Oman",
      "Palastine": "Palastine",
      "Qatar": "Qatar",
      "Your name": "Your name",
      "Phone number": "Phone number",
      "Birth date": "Birth date",
      "Email": "Email",
      "Password": "Password",
      "Password confirmation": "Password confirmation",
      "Or sign with": "Or sign with",
      "Facebook": "Facebook",
      "Google": "Google",
      "Forget password ?": "Forget password ?",
      "Already have an account?  ": "Already have an account?  ",
      "Don't have an account?  ": "Don't have an account?  ",
      "Sign in": "Sign up",
      "Sign up": "Register",
      "Enter your name please": "Enter your name please",
      "Enter your phone number please": "Enter your phone number please",
      "Enter your birth date please": "Enter your birth date please",
      "Enter your email please": "Enter your email please",
      "Your email must contain '@' ": "Your email must contain '@' ",
      "Your email must contain '.' ": "Your email must contain '.' ",
      "Enter your password please": "Enter your password please",
      "Password mustn't less than 8 characters": "Password mustn't less than 8 characters",
      "Enter your confirmation password please": "Enter your confirmation password please",
      "Password doesn't match": "Password doesn't match",
      "OTP Code": "OTP Code",
      "Please enter OTP code": "Please enter OTP code",
      "Check": "Check",
      "Reset password":  "Reset password",
      "Set Password": "Set Password",
      "Please enter your account mobile number": "Please enter your account mobile number",
      "Continue": "Continue",
      "Set new Password": "Set new Password",
      "New Password": "New Password",
      "Please enter the new password": "Please enter the new password"
    }
  };

}